/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a username for a JWT access token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "username": "alice"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Successful login. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /**
                 * @description Authentication failed. The `message` distinguishes the cause:
                 *     `user not found` or `user disabled`. Unexpected internal failures
                 *     collapse to a generic `unauthorized`.
                 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's sessions, newest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session list (empty array when none exist). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionListResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /**
         * Create a new session.
         * @description The server mints a UUID v7 session_id, persists the session row, and
         *     returns it. Clients must create a session before sending messages.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session created successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateSessionResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a session owned by the authenticated user.
         * @description Archives the session and all of its titles/messages verbatim into the
         *     `*_deleted` mirror tables, purges the live rows (archive + purge is a
         *     single atomic transaction), and removes the warm-tier session file.
         *     Redis cache entries (`session:{id}`, `msgs:{id}`) are intentionally not
         *     cleared; every read path re-validates ownership against MySQL first, so
         *     stale cache keys are unreachable until they expire on TTL. Deleting a
         *     session that does not exist or belongs to another user returns 404; the
         *     existence of another user's session is never disclosed.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the session to delete. */
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update the title of a session owned by the authenticated user.
         * @description Sets a manual title for the session. Manual titles are not overwritten
         *     by asynchronous AI title generation and the session's update_time is
         *     refreshed so the session appears first in the list.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the session to update. */
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTitleRequest"];
                };
            };
            responses: {
                /** @description Title updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateTitleResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the messages of a session with cursor pagination.
         * @description Returns the full event stream of a session owned by the authenticated
         *     user. Messages are ordered by `(msg_time, msg_index)` ascending by
         *     default; use `order=desc` to retrieve newest first. Pass
         *     `page_token` from the previous response to advance pages.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque cursor from the previous page's `next_page_token`. */
                    page_token?: string;
                    /** @description Number of messages per page. Values above 200 are clamped. */
                    page_size?: number;
                    /** @description Sort order for `(msg_time, msg_index)`. */
                    order?: "asc" | "desc";
                };
                header?: never;
                path: {
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated message list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionMessagesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /**
         * Send a user message and stream the agent's response as SSE.
         * @description The session must already exist and belong to the authenticated user.
         *     Sending to a non-existent session or another user's session returns 404.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /**
                 * @description Server-Sent Events stream. Each event frame is `id: <cursor>`,
                 *     `event: <type>`, and `data: <json>` followed by a blank line
                 *     (turn-detach-resume: the `id` line carries the run event log's
                 *     stream entry id; native EventSource clients replay it as
                 *     `Last-Event-ID` when resuming via
                 *     `GET /api/v1/sessions/{session_id}/turns/{run_id}/events`).
                 *     The response carries an `X-Run-Id` header (the run id, equal to
                 *     the request's trace id); every event's `meta.run_id` carries the
                 *     same value. Disconnecting from this stream does NOT cancel the
                 *     turn — cancel explicitly via the cancel endpoint.
                 *     Event types: `agent_start`, `token`, `reasoning`, `tool_call`, `tool_result`,
                 *     `agent_end`, `agent_error`, `done`. The `done` event is always the final event.
                 */
                200: {
                    headers: {
                        /** @description The run id of this turn (equals the request's trace id) — the cancel/resume target. */
                        "X-Run-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SSEAgentStart"] | components["schemas"]["SSEToken"] | components["schemas"]["SSEReasoning"] | components["schemas"]["SSEToolCall"] | components["schemas"]["SSEToolResult"] | components["schemas"]["SSEAgentEnd"] | components["schemas"]["SSEAgentError"] | components["schemas"]["SSEDone"];
                    };
                };
                /**
                 * @description Malformed body, or a rejected per-request model selection
                 *     (per-request-model-selection): `INVALID_MODEL` (unknown catalog
                 *     name) or `INVALID_EFFORT` (invalid effort value, non-`none`
                 *     effort explicitly requested on a `thinking: false` entry, or an
                 *     effort conflicting with a configured agent `output_schema`).
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /**
                 * @description The session already has a running turn (single active run per
                 *     session). The error object carries the active `run_id` so the
                 *     client can attach to the running turn instead of retrying.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "SESSION_BUSY";
                                message: string;
                                /** @description The currently running turn's run id (attach target). */
                                run_id: string;
                            };
                        };
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/turns/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running turn by run id (turn-detach-resume).
         * @description Cancels the turn identified by `run_id` and releases its resources.
         *     Three outcomes: the run is in THIS agent process (cancelled
         *     immediately, partial output persists through the interrupted-turn
         *     path), the run heartbeats on another replica (a Redis cancel flag is
         *     raised; the owning process cancels within one heartbeat period), or
         *     the run is dead (crashed process — force-cleared to `interrupted`,
         *     session unlocked). Cancelling an already-terminal run is idempotent
         *     and reports the terminal status. The run must belong to the caller
         *     and the path session, otherwise 404.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    session_id: string;
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancellation accepted (or already terminal). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TurnStatusResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/turns/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resume a run's event stream over SSE (turn-detach-resume).
         * @description Replays the run's event log from the beginning (or strictly after the
         *     `Last-Event-ID` request header) and then tails live output until the
         *     run reaches a terminal state — the endpoint a client uses when
         *     reopening a session whose previous request is still generating.
         *     Multiple concurrent subscribers (multiple tabs) are independent. A
         *     terminal-but-still-retained run replays fully and closes; a run whose
         *     retention window passed (or never existed) returns 410 — fall back to
         *     the ordinary message-history read. If a status-running run's process
         *     died, the stream replays what was logged, then emits a synthesized
         *     terminal `done` event carrying `usage.error = "interrupted..."`.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Stream entry id from a prior subscription's last received frame; resume strictly after it. */
                    "Last-Event-ID"?: string;
                };
                path: {
                    session_id: string;
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description Server-Sent Events stream of the run's events (same frame format
                 *     as POST /messages, including `id:` lines and `X-Run-Id` header).
                 *     The stream ends after the terminal `done` event.
                 */
                200: {
                    headers: {
                        /** @description The run id being replayed/tailed. */
                        "X-Run-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SSEAgentStart"] | components["schemas"]["SSEToken"] | components["schemas"]["SSEAgentError"] | components["schemas"]["SSEDone"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description The run is no longer replayable (retention window passed or unknown); read the ordinary message history instead. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List files in (a subdirectory of) the user's workspace. */
        get: {
            parameters: {
                query?: {
                    /** @description Optional workspace-relative subdirectory. Defaults to the workspace root. */
                    path?: string;
                    /** @description Whether to include hidden files and directories (names starting with '.'). Defaults to false. */
                    include_hidden?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File/dir entries, sorted (directories first, then name). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileListResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/download/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a workspace file using a URL token.
         * @description Authenticates via the `token` query parameter instead of the
         *     `Authorization` header. Designed for browser-native elements such as
         *     `<a download>`, `<img src>`, and PDF.js that cannot set custom headers.
         *     Returns `Content-Disposition: attachment` by default; pass `inline=1`
         *     for preview contexts. The response also carries
         *     `Cache-Control: private, no-store` and `Referrer-Policy: no-referrer`
         *     to mitigate the risk of the JWT leaking through caches or Referer headers.
         */
        get: {
            parameters: {
                query: {
                    /** @description JWT access token issued by POST /api/v1/auth/login. */
                    token: string;
                    /** @description Set to 1 to return Content-Disposition: inline for previews. */
                    inline?: 1;
                };
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file path (catch-all, may include `/`).
                     * @example reports/2026-q2.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File bytes; content-type reflects the file extension. */
                200: {
                    headers: {
                        /** @description attachment or inline, with ASCII and RFC 5987 filename values. */
                        "Content-Disposition"?: string;
                        "Cache-Control"?: string;
                        "Referrer-Policy"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Missing/empty `path`, or `path` resolves to a directory. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired query token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file into the user's workspace. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /** @description Destination subdirectory (empty/absent means root). */
                        path?: string;
                    };
                };
            };
            responses: {
                /** @description Upload succeeded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                /** @description Uploaded file exceeds the 50 MiB size limit. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a workspace file as raw bytes.
         * @description The `path` parameter is a workspace-relative path (which may contain
         *     slashes). `path` ending in `/content` selects the text-content
         *     endpoint instead. The content-type of the response reflects the
         *     file's extension.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file path (catch-all, may include `/`).
                     * @example reports/2026-q2.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File bytes; content-type varies by extension. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Path resolves to a directory. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        /**
         * Rename or move a workspace file or directory.
         * @description Renames or moves a file or directory within the user's workspace. When
         *     new_path resolves to an existing directory, the source is moved inside it
         *     as new_path/<basename> (the "drag into a folder" gesture). Otherwise the
         *     final destination must not already exist: if it does, the operation
         *     returns 409 unless `overwrite` is true, in which case an existing file
         *     destination is atomically replaced (overwriting a directory is rejected
         *     with 409 DEST_NOT_EMPTY; tree merge is not supported). No changes are
         *     made on any rejection.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative source file or directory path (catch-all, may include `/`).
                     * @example reports/old.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenameRequest"];
                };
            };
            responses: {
                /** @description Rename succeeded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RenameResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /**
                 * @description Final destination already exists, or (with overwrite) is an existing
                 *     directory.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        /**
         * Create an empty workspace file or directory.
         * @description Strict create of an empty file or directory selected by the body
         *     {"type": "file" | "directory"}. The path comes from the URL catch-all
         *     (like Rename, whose params live in the body). "Strict" means a target leaf
         *     that already exists — file OR directory — is rejected with 409
         *     ALREADY_EXISTS and left untouched; there is no check-then-create window,
         *     because file creation uses OpenFile(O_CREATE|O_EXCL) and directory
         *     creation uses os.Mkdir, both of which surface EEXIST on an existing leaf
         *     (so two concurrent creates of the same path resolve as one 200 and one
         *     409). Missing parent directories are auto-created (MkdirAll on the
         *     parent), so a nested path (e.g. a/b/c) is established in one call; the
         *     strict guarantee applies only to the leaf itself. This is distinct from
         *     PUT .../content, which is a create-or-replace for text content — POST
         *     creates empty nodes only. POST has no /content split, so it registers
         *     directly on the catch-all with no suffix dispatcher.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative path of the node to create (catch-all, may include `/`).
                     * @example notes/hello.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNodeRequest"];
                };
            };
            responses: {
                /** @description Node created; its relative path and kind. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateNodeResponse"];
                    };
                };
                /** @description Creating the workspace root (empty path), or a missing/invalid `type`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description A file or directory already exists at the target leaf. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        /**
         * Delete a workspace file or directory.
         * @description Removes a file or, when the path targets a directory, recursively
         *     removes the directory and everything beneath it. The path is validated
         *     with the same traversal / symlink-escape check as the read endpoints,
         *     so anything resolving outside the workspace is rejected with 403.
         *     Workspace files have no database source table, so nothing is archived —
         *     the entry is removed from the filesystem only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file or directory path (catch-all, may include `/`).
                     * @example reports/old
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File or directory deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a workspace file's text content as JSON. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace-relative file path (catch-all, may include `/`). */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Decoded text content of the file. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileContentResponse"];
                    };
                };
                /** @description File is binary or path is a directory. Use the download endpoint for binary files. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        /**
         * Create or replace a workspace file's text content atomically.
         * @description Symmetric write counterpart to GET .../content: an atomic, create-or-replace
         *     (HTTP PUT) text-content write. A missing target file is created (missing
         *     parents are auto-created); an existing file is fully replaced via a
         *     temp-file + rename, so a crash mid-write never truncates the destination.
         *     The body is capped at the server's max upload size, and only text is
         *     accepted — a NUL byte is rejected with 400 BINARY_FILE (binary/large files
         *     use POST .../upload). The `path` is the catch-all workspace-relative file
         *     path; a trailing `/content` selects this operation under the PUT catch-all.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file path (catch-all, may include `/`).
                     * @example notes/hello.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "content": "# Hello"
                     *     }
                     */
                    "application/json": components["schemas"]["WriteContentRequest"];
                };
            };
            responses: {
                /** @description Content written; the file's relative path and byte size. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileContentWriteResponse"];
                    };
                };
                /** @description Malformed body, the target is an existing directory, or the content is binary. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                413: components["responses"]["PayloadTooLarge"];
                500: components["responses"]["Internal"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}/onlyoffice-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and sign OnlyOffice edit + view configs for a workspace office file.
         * @description Returns server-signed DocEditor configs (`{server_url, edit, view}`, each
         *     mode an `{config, token}` pair) so the browser can open the file in either
         *     edit or view mode in OnlyOffice without a second round-trip. The OnlyOffice
         *     secret lives only in the backend config and never reaches the browser; each
         *     `token` is an HS256 JWT whose payload is that mode's `config`. `document.url`
         *     and `editorConfig.callbackUrl` point at the backend's internal origin and
         *     embed the caller's JWT as a query `token`; both modes share one freshly
         *     random `document.key` so reopening always re-converts. Shares the workspace
         *     catch-all with `/content`, dispatching on the trailing `/onlyoffice-config`
         *     suffix.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative office file path (catch-all, may include `/`).
                     * @example reports/2026-q2.docx
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed editor config. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnlyOfficeConfigResponse"];
                    };
                };
                /** @description The path resolves to a directory. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description OnlyOffice is not configured (secret empty); editing is disabled. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}/onlyoffice-version-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and sign an OnlyOffice view-only config for a historical version.
         * @description Returns a server-signed view-only DocEditor config
         *     (`{server_url, view:{config, token}}`) so the browser can preview a
         *     specific historical version of a workspace office file in OnlyOffice.
         *     The caller supplies the `versionId` (obtained elsewhere from the
         *     office-vers service); `document.url` points at office-vers for that
         *     version and carries no credential. The OnlyOffice secret lives only in
         *     the backend; `view.token` is an HS256 JWT whose payload is the
         *     `view.config`. Unlike the live-file `/onlyoffice-config` endpoint:
         *     `document.url` targets office-vers (not the backend), `document.key` is
         *     deterministic per `(path, versionId)` (so conversions are cached/shared),
         *     the config is view-only with no `callbackUrl`/`forcesave`, and the local
         *     workspace file is NOT stat-checked (the version's source of truth is
         *     office-vers). Shares the workspace catch-all, dispatching on the
         *     trailing `/onlyoffice-version-config` suffix.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The office-vers (MinIO) version id of the historical version to
                     *     preview. Obtained from the office-vers version-history listing.
                     * @example 7a604dc7-719f-426f-88c4-642313fd2860
                     */
                    versionId: string;
                };
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative office file path (catch-all, may include `/`).
                     * @example reports/2026-q2.docx
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed view-only editor config for the requested version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnlyOfficeVersionConfigResponse"];
                    };
                };
                /** @description The `versionId` query parameter is missing. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description OnlyOffice is not configured (`secret` or `version_service_url` empty). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/onlyoffice-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive an OnlyOffice document-save callback and persist it.
         * @description Endpoint the OnlyOffice DocumentServer POSTs to when a document is saved.
         *     Authenticates via the `token` query parameter (the user JWT embedded in
         *     the signed `callbackUrl`) instead of the Authorization header, since the
         *     callback originates from the DocumentServer container. For save statuses
         *     (2/6) it downloads the edited file from `url` — host-allowlisted to the
         *     configured DocumentServer to mitigate SSRF — and atomically overwrites the
         *     workspace file (capped at the upload size limit). Non-save statuses are
         *     acknowledged without writing. Outcomes use OnlyOffice's `{"error": N}`
         *     convention (0 = ok, non-0 = retry); auth/path errors are normal HTTP 4xx.
         */
        post: {
            parameters: {
                query: {
                    /**
                     * @description Workspace-relative file path to overwrite.
                     * @example reports/2026-q2.docx
                     */
                    path: string;
                    /** @description JWT access token (embedded in the signed callbackUrl). */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnlyOfficeCallbackRequest"];
                };
            };
            responses: {
                /** @description Callback processed; body reports success or a retryable error. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnlyOfficeCallbackResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description OnlyOffice is not configured (secret empty); editing is disabled. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the MCP-sourced tool catalogue.
         * @description Returns only MCP-sourced tools. The catalogue has two parts: proxy
         *     tools advertised by configured operator (global) MCP servers, and the
         *     cached tools of the caller's per-user MCP servers (read from the
         *     workspace config cache; no live connections are made). Built-in tools
         *     (`xizhi_*`, `webfetch`, executor, `luban_*`) and synthetic `invoke_*`
         *     dispatch tools are excluded. Each entry follows the OpenAI
         *     function-tool shape (`type: function`) and carries a `server` field
         *     attributing it to its MCP source (an operator server name or a
         *     per-user server name). The per-user view is cache-based; freshness is
         *     maintained by the agent-runtime cache writers (`mcp_list_tools`,
         *     `mcp_add_server`, `mcp_call`). A missing/empty per-user config yields
         *     only the operator tools; a single malformed per-user server is
         *     omitted while the rest still return.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tool list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MCPToolsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's skills. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skill list (empty array when none exist). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkillsResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the selectable model catalog (per-request-model-selection).
         * @description Returns the deployment's model catalog (`openai.models`, mandatory),
         *     the default model name, and the deployment default reasoning effort
         *     (`default_reasoning_effort`) for chat-request `model`/`reasoning_effort`
         *     selection. Served by the api role only (the agent role does not
         *     register this endpoint).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Model catalog and default. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable machine-readable error code.
                 * @example BAD_REQUEST
                 */
                code: string;
                /**
                 * @description Human-readable error description.
                 * @example invalid request body
                 */
                message: string;
            };
        };
        LoginRequest: {
            username: string;
            /** @description User password, verified against the seed-created bcrypt hash. Required only when auth.password_required is true (the default); in passwordless mode the password, if sent, is ignored. */
            password?: string;
        };
        LoginResponse: {
            /** @description The authenticated user's unique ID. */
            user_id: string;
            /** @description Signed JWT to send as `Bearer` in subsequent requests. */
            access_token: string;
            /**
             * Format: int64
             * @description Token expiry as a Unix timestamp (seconds).
             */
            expire: number;
            /**
             * @example Bearer
             * @enum {string}
             */
            token_type: "Bearer";
        };
        SessionListEntry: {
            session_id: string;
            title: string;
            /**
             * Format: date-time
             * @description RFC3339 timestamp of the last update.
             */
            update_time: string;
            /**
             * @description Whether a turn is currently running for this session
             *     (turn-detach-resume). True while the session's active-run claim
             *     exists; clients use it to offer resume (attach to
             *     `turns/{run_id}/events`) and a cancel affordance.
             */
            generating: boolean;
            /**
             * @description The active turn's run id — the attach/cancel target. Present only
             *     while `generating` is true. This is the reload discovery path: a
             *     reloaded page has lost the `X-Run-Id` header and event meta it
             *     saw when the turn started, so it recovers the run id from here.
             */
            run_id?: string;
        };
        SessionListResponse: {
            sessions: components["schemas"]["SessionListEntry"][];
        };
        CreateSessionResponse: {
            /**
             * Format: uuid
             * @description Server-generated UUID v7 session identifier.
             * @example 018f9b8a-7c1a-7e6a-8e6a-6c1a7c1a7c1a
             */
            session_id: string;
        };
        Message: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            session_id: string;
            /** Format: date-time */
            msg_time: string;
            /** @enum {string} */
            agent: "user" | "Confucius" | "Chongzhi" | "Liang";
            msg_index: number;
            /** @enum {string} */
            role: "user" | "assistant" | "tool" | "";
            /** @enum {string} */
            event_type: "message" | "token" | "tool_call" | "tool_result" | "agent_start" | "agent_end" | "agent_error" | "reasoning";
            content: string;
            /** Format: uuid */
            trace_id: string;
            /** @description Idempotency key minted at persistence time. Backs the Redis-first write-behind delivery: duplicate insert attempts of the same logical message collapse to one row. Rows carry either a deterministic "{trace_id}:{msg_index}" key (the mid-turn-compaction flush path, migration 013) or a UUID v7 (legacy write-behind minting). Null on rows written before migration 012. */
            client_msg_id?: string | null;
            /** @description Sub-agent invocation run identity (subagent-run-identity capability): the id of the parent invoke_* tool_call that spawned the producing Run. Present only on rows emitted by a sub-agent (Chongzhi/Liang); Confucius top-level rows and user rows omit it, and rows written before migration 014 are null. Rows stay in arrival order (msg_time, msg_index) — consumers regroup interleaved same-agent rows by (agent, run_id) to recover each invocation's coherent output. */
            run_id?: string | null;
            /** Format: date-time */
            update_time: string;
        };
        SessionMessagesResponse: {
            messages: components["schemas"]["Message"][];
            /** @description Opaque cursor for the next page. Absent on the final page. */
            next_page_token?: string;
        };
        SendMessageRequest: {
            /** @description User message text (must be non-empty). */
            content: string;
            /**
             * @description Selects the turn's model from the mandatory `openai.models`
             *     catalog (per-request-model-selection). The selection applies
             *     uniformly to all three agents; omitted → the default entry
             *     (`openai.default_model`, else the first entry). Unknown names
             *     return 400 `INVALID_MODEL`.
             */
            model?: string;
            /**
             * @description Selects the turn's thinking level; omitted → the deployment
             *     default (`openai.default_reasoning_effort`, itself defaulting to
             *     `none`). On a `thinking: true` entry, `none` is sent to the
             *     provider as a literal value (it does NOT mean "omit the
             *     parameter") — compatible gateways then disable thinking for the
             *     turn. A non-`none` value explicitly requested on a
             *     `thinking: false` entry returns 400 `INVALID_EFFORT`; a
             *     non-`none` deployment default landing on such an entry is clamped
             *     to `none` (WARN) and the turn proceeds.
             * @enum {string}
             */
            reasoning_effort?: "none" | "low" | "medium" | "high" | "xhigh" | "max";
        };
        TurnStatusResponse: {
            run_id: string;
            /**
             * @description `cancelling` — accepted; the owning process will finalize the run
             *     (persisting partial output). The remaining values are terminal
             *     states reported by idempotent cancels of finished runs.
             * @enum {string}
             */
            status: "cancelling" | "running" | "done" | "error" | "cancelled" | "interrupted";
        };
        SSEAgentStart: {
            /** @enum {string} */
            type: "agent_start";
            agent: string;
            meta?: {
                /** @description Present only on sub-agent events; the parent invoke_* tool_call id (run identity). */
                parent_tool_call_id?: string;
                /** @description The owning turn run id; present on every event frame (turn-detach-resume). */
                run_id?: string;
            };
        };
        SSEToken: {
            /** @enum {string} */
            type: "token";
            agent: string;
            /** @description Incremental text token. */
            content: string;
            meta?: {
                /** @description Present only on sub-agent events; the parent invoke_* tool_call id (run identity). */
                parent_tool_call_id?: string;
                /** @description The owning turn run id; present on every event frame (turn-detach-resume). */
                run_id?: string;
            };
        };
        SSEReasoning: {
            /** @enum {string} */
            type: "reasoning";
            agent: string;
            /** @description Incremental reasoning/thinking token. */
            content: string;
            meta?: {
                /** @description Present only on sub-agent events; the parent invoke_* tool_call id (run identity). */
                parent_tool_call_id?: string;
                /** @description The owning turn run id; present on every event frame (turn-detach-resume). */
                run_id?: string;
            };
        };
        SSEToolCall: {
            /** @enum {string} */
            type: "tool_call";
            agent: string;
            /** @description Tool name. */
            content: string;
            meta?: {
                /** @description Correlates this call with its tool_result event. */
                tool_call_id: string;
                args?: {
                    [key: string]: unknown;
                };
                /** @description Present only on sub-agent events; the parent invoke_* tool_call id (run identity). */
                parent_tool_call_id?: string;
                /** @description The owning turn run id; present on every event frame (turn-detach-resume). */
                run_id?: string;
            };
        };
        /**
         * @description Outcome of a tool invocation. Pairs with the preceding `tool_call` event
         *     via `meta.tool_call_id`. `content` is the same string fed back to the
         *     model as the role="tool" message body: for registry tools the uniform
         *     status envelope `{"status":0,"result":...}` / `{"status":1,"error":...}`;
         *     for invoke_* sub-agent dispatches, the sub-agent's output (or error text)
         *     verbatim. The status envelope is the sole channel for a registry-tool
         *     failure: no `agent_error` event is emitted for tool errors (the frontend
         *     renders tool errors from `content`'s `status` field).
         */
        SSEToolResult: {
            /** @enum {string} */
            type: "tool_result";
            agent: string;
            /** @description Serialized tool result (status/result envelope), sub-agent output, or error text. */
            content: string;
            meta?: {
                /** @description Matches the meta.tool_call_id of the originating tool_call event. */
                tool_call_id: string;
                /** @description Present only on sub-agent events; the parent invoke_* tool_call id (run identity). */
                parent_tool_call_id?: string;
                /** @description The owning turn run id; present on every event frame (turn-detach-resume). */
                run_id?: string;
            };
        };
        SSEAgentEnd: {
            /** @enum {string} */
            type: "agent_end";
            agent: string;
            meta?: {
                /** @description Present only on sub-agent events; the parent invoke_* tool_call id (run identity). */
                parent_tool_call_id?: string;
                /** @description The owning turn run id; present on every event frame (turn-detach-resume). */
                run_id?: string;
            };
        };
        /**
         * @description An agent-level failure or control signal. NOT emitted for registry-tool
         *     failures (those are carried solely by the SSEToolResult status envelope).
         *     `meta.error_code` is one of: `llm_error` (LLM call failed), `unknown_tool`
         *     (no tool registry / unknown sub-agent tool), `bad_args` (malformed
         *     sub-agent invoke arguments), `retry` (in-progress sub-agent retry, paired
         *     with `meta.retry=true`), `round_cap_exhausted` (round-cap wrap-up round
         *     produced no content).
         */
        SSEAgentError: {
            /** @enum {string} */
            type: "agent_error";
            agent: string;
            /** @description Error message. */
            content: string;
            meta?: {
                error_code?: string;
                /** @description Present only on sub-agent events; the parent invoke_* tool_call id (run identity). */
                parent_tool_call_id?: string;
                /** @description The owning turn run id; present on every event frame (turn-detach-resume). */
                run_id?: string;
            };
        };
        SSEDone: {
            /** @enum {string} */
            type: "done";
            meta: {
                /**
                 * @description Per-turn token-usage breakdown. Authoritative shape (turn-cost-tracking
                 *     spec): `{total, by_agent, meta}`.
                 *
                 *     `total` is the aggregate turn usage. `by_agent` carries the per-agent
                 *     attribution keyed by agent display name (always includes "Confucius",
                 *     plus one entry per dispatched sub-agent). `meta` records turn-level
                 *     orchestration facts: `parallel` (true when any assistant round
                 *     dispatched >=2 tool_calls) and `sub_agent_invocations` (the invoke_*
                 *     tool names dispatched this turn, in dispatch order, deduplicated).
                 *
                 *     Legacy flat top-level fields (`prompt_tokens`, `completion_tokens`,
                 *     `total_tokens`, `reasoning_tokens`) have been MOVED under `total`;
                 *     consumers reading `usage.total_tokens` must migrate to
                 *     `usage.total.total_tokens`.
                 */
                usage: {
                    total: components["schemas"]["SSEUsageTokens"];
                    /** @description Per-agent usage keyed by agent display name (Confucius, Chongzhi, Liang). */
                    by_agent: {
                        [key: string]: components["schemas"]["SSEUsageTokens"];
                    };
                    meta: {
                        /** @description invoke_* tool names dispatched this turn, dispatch order, deduplicated. */
                        sub_agent_invocations: string[];
                        /** @description True when any assistant round dispatched >=2 tool_calls. */
                        parallel: boolean;
                    };
                    /** @description Present only when the turn completed with an error; the failure message. */
                    error?: string;
                };
            };
        };
        SSEUsageTokens: {
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
            /** @description Present only for thinking/reasoning runs (reasoning_tokens > 0). */
            reasoning_tokens?: number;
        };
        FileEntry: {
            name: string;
            /** @enum {string} */
            type: "file" | "dir";
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            update_time: string;
        };
        FileListResponse: {
            files: components["schemas"]["FileEntry"][];
        };
        UploadResponse: {
            /** @description Workspace-relative path of the stored file. */
            path: string;
            /** Format: int64 */
            size: number;
        };
        FileContentResponse: {
            path: string;
            content: string;
            size: number;
        };
        /** @description Body for PUT .../files/{path}/content. */
        WriteContentRequest: {
            /** @description Full text body to write as a whole-file replace (create-or-replace, like xizhi_write_file). */
            content: string;
        };
        /** @description Response for PUT .../files/{path}/content. */
        FileContentWriteResponse: {
            /** @description Workspace-relative path of the written file. */
            path: string;
            /** @description Number of bytes written. */
            size: number;
        };
        UpdateTitleRequest: {
            /** @description New session title (max 20 characters; longer values are truncated). */
            title: string;
        };
        UpdateTitleResponse: {
            session_id: string;
            title: string;
            /** Format: date-time */
            update_time: string;
        };
        RenameRequest: {
            /** @description Workspace-relative destination path. */
            new_path: string;
            /**
             * @description When true and the final destination is an existing file, atomically
             *     replace it. Default false preserves the 409-on-existing-file behavior.
             *     Overwriting an existing directory is rejected with 409 DEST_NOT_EMPTY;
             *     tree merge is not supported.
             * @default false
             */
            overwrite: boolean;
        };
        RenameResponse: {
            old_path: string;
            new_path: string;
        };
        /**
         * @description Body for POST .../files/{path}. The target path comes from the URL
         *     catch-all (like Rename); the body selects whether to create a file or a
         *     directory. The created node is empty — content writes use PUT .../content.
         */
        CreateNodeRequest: {
            /**
             * @description Kind of node to create. Strict create: an existing leaf of either kind returns 409 ALREADY_EXISTS.
             * @enum {string}
             */
            type: "file" | "directory";
        };
        /** @description Response for POST .../files/{path}. */
        CreateNodeResponse: {
            /** @description Workspace-relative path of the created node. */
            path: string;
            /**
             * @description Kind of node created (echoes the request type).
             * @enum {string}
             */
            type: "file" | "directory";
        };
        MCPTool: {
            /**
             * @example function
             * @enum {string}
             */
            type: "function";
            name: string;
            description: string;
            /** @description JSON Schema describing the tool's input parameters. */
            parameters: {
                [key: string]: unknown;
            };
            /** @description The MCP source this tool belongs to — an operator (global) MCP server name or a per-user MCP server name. */
            server: string;
        };
        MCPToolsResponse: {
            tools: components["schemas"]["MCPTool"][];
        };
        SkillEntry: {
            /** @description Skill identifier (the subdirectory name containing SKILL.md). */
            name: string;
            /** @description Same as `name`; the skill directory name. */
            filename: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            update_time: string;
        };
        SkillsResponse: {
            skills: components["schemas"]["SkillEntry"][];
        };
        /**
         * @description The selectable model catalog (per-request-model-selection). `thinking`
         *     tells clients whether `reasoning_effort` values other than `none` are
         *     valid for the model (and which wire family the model uses).
         *     `default_reasoning_effort` is the deployment-level default thinking
         *     effort (`openai.default_reasoning_effort`, `"none"` when unset) — the
         *     natural preselection for an effort picker. Each turn's resolved model
         *     is recorded in run meta (`GET .../turns/{run_id}/events` payloads) and
         *     the `turn_usage` table's `model` column (NULL on pre-migration rows)
         *     for per-model cost aggregation.
         */
        ModelsResponse: {
            models: components["schemas"]["ModelEntry"][];
            /** @description The default model name (openai.default_model, else the first catalog entry). */
            default: string;
            /**
             * @description The deployment default reasoning effort applied to requests that omit `reasoning_effort`.
             * @enum {string}
             */
            default_reasoning_effort: "none" | "low" | "medium" | "high" | "xhigh" | "max";
        };
        ModelEntry: {
            /** @description Model name — the value a request's `model` parameter accepts. */
            name: string;
            /** @description The model's context window; the context-compaction threshold for turns selecting it (0.8 × this value). */
            max_context_tokens: number;
            /** @description Whether the model supports reasoning (gates non-`none` reasoning_effort values). */
            thinking: boolean;
        };
        /**
         * @description Server-signed OnlyOffice DocEditor configs for both edit and view modes.
         *     The browser loads api.js from `server_url` and instantiates
         *     `new DocsAPI.DocEditor(id, {...config, token})` for whichever mode it
         *     needs. The OnlyOffice secret never leaves the server — each `token` is
         *     an HS256 JWT whose payload is that mode's `config`, verifiable by the
         *     DocumentServer with the same secret. Because the token signs the whole
         *     config, the frontend cannot switch modes by mutating a config in place;
         *     it must use the pre-signed edit or view token. Both modes share one
         *     freshly random `document.key` (per request).
         */
        OnlyOfficeConfigResponse: {
            /** @description Browser-facing DocumentServer origin (api.js is loaded from here). */
            server_url: string;
            edit: components["schemas"]["OnlyOfficeModeConfig"];
            view: components["schemas"]["OnlyOfficeModeConfig"];
        };
        /**
         * @description One signed DocEditor config (edit or view). `config` is the editor
         *     config object; `token` is the HS256 JWT signing exactly that `config`
         *     with the OnlyOffice secret. The edit and view tokens are distinct.
         */
        OnlyOfficeModeConfig: {
            /**
             * @description DocEditor config object. `edit.config` carries `documentType`
             *     (word/cell/slide), `document{fileType, key, title, url,
             *     permissions{edit:true, download:true}}` and `editorConfig{mode:"edit",
             *     callbackUrl, customization{forcesave:true}, user}`. `view.config` is
             *     identical except `document.permissions.edit` is `false` and
             *     `editorConfig{mode:"view", callbackUrl, user}` carries no
             *     `customization.forcesave`. Both share the same `document.key`
             *     (freshly random per request); `document.url` and
             *     `editorConfig.callbackUrl` are rooted at the backend's internal origin
             *     and carry the user JWT as a query `token`.
             */
            config: {
                [key: string]: unknown;
            };
            /** @description HS256 JWT signing this mode's `config` with the OnlyOffice secret; edit and view tokens differ. */
            token: string;
        };
        /**
         * @description Server-signed OnlyOffice DocEditor config for viewing a specific
         *     historical version (view-only). Mirrors one mode of
         *     OnlyOfficeConfigResponse — a single `{config, token}` pair nested under
         *     `view` — so the frontend reuses its existing `view` consumption path. A
         *     historical version is immutable, so only the view mode is returned (no
         *     edit). `document.url` points at the external office-vers service
         *     (`{version_service_url}/documents/{userUUID}/{path}?action=version&versionId=<vid>`)
         *     and carries NO credential (office-vers is unauthenticated by design);
         *     `document.key` is derived deterministically from `(path, versionId)`
         *     (`base32(sha256(path + ":" + versionId))`) so OnlyOffice caches and shares
         *     the conversion across opens/users; the config carries no `callbackUrl`
         *     and no `customization.forcesave` (nothing to save back to an immutable
         *     version).
         */
        OnlyOfficeVersionConfigResponse: {
            /** @description Browser-facing DocumentServer origin (api.js is loaded from here). */
            server_url: string;
            view: components["schemas"]["OnlyOfficeModeConfig"];
        };
        /**
         * @description OnlyOffice DocumentServer save callback. `status` 2/6 carry the edited
         *     document at `url` and trigger a download + workspace overwrite; other
         *     statuses (1/3/4/7) are acknowledged without writing.
         */
        OnlyOfficeCallbackRequest: {
            /** @description Document state (1=being edited, 2=ready for saving, 3/7=saving error, 4=closed no changes, 6=forcesave). */
            status?: number;
            /** @description Document key the config was signed with. */
            key?: string;
            /** @description URL of the edited document to download (only present on save statuses). */
            url?: string;
        };
        /**
         * @description OnlyOffice callback contract. `error` 0 = success; non-0 makes the
         *     DocumentServer retry. Auth/path errors are reported as normal HTTP 4xx,
         *     not through this body.
         */
        OnlyOfficeCallbackResponse: {
            /** @description 0 on success, non-0 to trigger a DocumentServer retry. */
            error: number;
        };
    };
    responses: {
        /** @description Malformed request body or missing field. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation not permitted (e.g. path outside workspace). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Target resource already exists. */
        AlreadyExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Uploaded file exceeds the size limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
