/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a username for a JWT access token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "username": "alice"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Successful login. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /**
                 * @description Authentication failed. The `message` distinguishes the cause:
                 *     `user not found` or `user disabled`. Unexpected internal failures
                 *     collapse to a generic `unauthorized`.
                 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's sessions, newest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session list (empty array when none exist). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionListResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /**
         * Create a new session.
         * @description The server mints a UUID v7 session_id, persists the session row, and
         *     returns it. Clients must create a session before sending messages.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session created successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateSessionResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a session owned by the authenticated user.
         * @description Archives the session and all of its titles/messages verbatim into the
         *     `*_deleted` mirror tables, purges the live rows (archive + purge is a
         *     single atomic transaction), and removes the warm-tier session file.
         *     Redis cache entries (`session:{id}`, `msgs:{id}`) are intentionally not
         *     cleared; every read path re-validates ownership against MySQL first, so
         *     stale cache keys are unreachable until they expire on TTL. Deleting a
         *     session that does not exist or belongs to another user returns 404; the
         *     existence of another user's session is never disclosed.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the session to delete. */
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update the title of a session owned by the authenticated user.
         * @description Sets a manual title for the session. Manual titles are not overwritten
         *     by asynchronous AI title generation and the session's update_time is
         *     refreshed so the session appears first in the list.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the session to update. */
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTitleRequest"];
                };
            };
            responses: {
                /** @description Title updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateTitleResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the messages of a session with cursor pagination.
         * @description Returns the full event stream of a session owned by the authenticated
         *     user. Messages are ordered by `(msg_time, msg_index)` ascending by
         *     default; use `order=desc` to retrieve newest first. Pass
         *     `page_token` from the previous response to advance pages.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque cursor from the previous page's `next_page_token`. */
                    page_token?: string;
                    /** @description Number of messages per page. Values above 200 are clamped. */
                    page_size?: number;
                    /** @description Sort order for `(msg_time, msg_index)`. */
                    order?: "asc" | "desc";
                };
                header?: never;
                path: {
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated message list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionMessagesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /**
         * Send a user message and stream the agent's response as SSE.
         * @description The session must already exist and belong to the authenticated user.
         *     Sending to a non-existent session or another user's session returns 404.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /**
                 * @description Server-Sent Events stream. Each event is two lines:
                 *     `event: <type>` and `data: <json>` followed by a blank line.
                 *     Event types: `agent_start`, `token`, `reasoning`, `tool_call`, `agent_end`,
                 *     `agent_error`, `done`. The `done` event is always the final event.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SSEAgentStart"] | components["schemas"]["SSEToken"] | components["schemas"]["SSEReasoning"] | components["schemas"]["SSEToolCall"] | components["schemas"]["SSEAgentEnd"] | components["schemas"]["SSEAgentError"] | components["schemas"]["SSEDone"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List files in (a subdirectory of) the user's workspace. */
        get: {
            parameters: {
                query?: {
                    /** @description Optional workspace-relative subdirectory. Defaults to the workspace root. */
                    path?: string;
                    /** @description Whether to include hidden files and directories (names starting with '.'). Defaults to false. */
                    include_hidden?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File/dir entries, sorted (directories first, then name). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileListResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/download/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a workspace file using a URL token.
         * @description Authenticates via the `token` query parameter instead of the
         *     `Authorization` header. Designed for browser-native elements such as
         *     `<a download>`, `<img src>`, and PDF.js that cannot set custom headers.
         *     Returns `Content-Disposition: attachment` by default; pass `inline=1`
         *     for preview contexts. The response also carries
         *     `Cache-Control: private, no-store` and `Referrer-Policy: no-referrer`
         *     to mitigate the risk of the JWT leaking through caches or Referer headers.
         */
        get: {
            parameters: {
                query: {
                    /** @description JWT access token issued by POST /api/v1/auth/login. */
                    token: string;
                    /** @description Set to 1 to return Content-Disposition: inline for previews. */
                    inline?: 1;
                };
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file path (catch-all, may include `/`).
                     * @example reports/2026-q2.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File bytes; content-type reflects the file extension. */
                200: {
                    headers: {
                        /** @description attachment or inline, with ASCII and RFC 5987 filename values. */
                        "Content-Disposition"?: string;
                        "Cache-Control"?: string;
                        "Referrer-Policy"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Missing/empty `path`, or `path` resolves to a directory. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired query token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file into the user's workspace. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /** @description Destination subdirectory (empty/absent means root). */
                        path?: string;
                    };
                };
            };
            responses: {
                /** @description Upload succeeded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                /** @description Uploaded file exceeds the 50 MiB size limit. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a workspace file as raw bytes.
         * @description The `path` parameter is a workspace-relative path (which may contain
         *     slashes). `path` ending in `/content` selects the text-content
         *     endpoint instead. The content-type of the response reflects the
         *     file's extension.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file path (catch-all, may include `/`).
                     * @example reports/2026-q2.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File bytes; content-type varies by extension. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Path resolves to a directory. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        /**
         * Rename or move a workspace file or directory.
         * @description Renames or moves a file or directory within the user's workspace. When
         *     new_path resolves to an existing directory, the source is moved inside it
         *     as new_path/<basename> (the "drag into a folder" gesture). Otherwise the
         *     final destination must not already exist: if it does, the operation
         *     returns 409 unless `overwrite` is true, in which case an existing file
         *     destination is atomically replaced (overwriting a directory is rejected
         *     with 409 DEST_NOT_EMPTY; tree merge is not supported). No changes are
         *     made on any rejection.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative source file or directory path (catch-all, may include `/`).
                     * @example reports/old.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenameRequest"];
                };
            };
            responses: {
                /** @description Rename succeeded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RenameResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /**
                 * @description Final destination already exists, or (with overwrite) is an existing
                 *     directory.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        /**
         * Create an empty file or directory (strict create).
         * @description Strict create of an empty leaf selected by the body {"type": "file"
         *     | "directory"}. A target leaf that already exists — file OR directory —
         *     is rejected with 409 ALREADY_EXISTS and left untouched (file creation
         *     uses OpenFile(O_CREATE|O_EXCL) and directory creation uses os.Mkdir, so
         *     there is no check-then-create window). Missing parent directories are
         *     auto-created (MkdirAll on the parent), so a nested path like a/b/c is
         *     established in one call; the strict guarantee applies only to the leaf.
         *     This is distinct from PUT .../content, which is a create-or-replace for
         *     text content — Create produces empty nodes only. Creating the workspace
         *     root itself (empty/"/" path) is rejected with 400 BAD_REQUEST; a missing
         *     or invalid type returns 400.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file or directory path (catch-all, may include `/`).
                     * @example notes/hello.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNodeRequest"];
                };
            };
            responses: {
                /** @description Node created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateNodeResponse"];
                    };
                };
                /** @description Empty/"/" path, or missing/invalid type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description A leaf (file or directory) already exists at the path. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        /**
         * Delete a workspace file or directory.
         * @description Removes a file or, when the path targets a directory, recursively
         *     removes the directory and everything beneath it. The path is validated
         *     with the same traversal / symlink-escape check as the read endpoints,
         *     so anything resolving outside the workspace is rejected with 403.
         *     Workspace files have no database source table, so nothing is archived —
         *     the entry is removed from the filesystem only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file or directory path (catch-all, may include `/`).
                     * @example reports/old
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File or directory deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a workspace file's text content as JSON. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace-relative file path (catch-all, may include `/`). */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Decoded text content of the file. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileContentResponse"];
                    };
                };
                /** @description File is binary or path is a directory. Use the download endpoint for binary files. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        /**
         * Create or replace a workspace file's text content atomically.
         * @description Symmetric write counterpart to GET .../content: an atomic, create-or-replace
         *     (HTTP PUT) text-content write. A missing target file is created (missing
         *     parents are auto-created); an existing file is fully replaced via a
         *     temp-file + rename, so a crash mid-write never truncates the destination.
         *     The body is capped at the server's max upload size, and only text is
         *     accepted — a NUL byte is rejected with 400 BINARY_FILE (binary/large files
         *     use POST .../upload). The `path` is the catch-all workspace-relative file
         *     path; a trailing `/content` selects this operation under the PUT catch-all.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file path (catch-all, may include `/`).
                     * @example notes/hello.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "content": "# Hello"
                     *     }
                     */
                    "application/json": components["schemas"]["WriteContentRequest"];
                };
            };
            responses: {
                /** @description Content written; the file's relative path and byte size. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileContentWriteResponse"];
                    };
                };
                /** @description Malformed body, the target is an existing directory, or the content is binary. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                413: components["responses"]["PayloadTooLarge"];
                500: components["responses"]["Internal"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}/onlyoffice-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and sign OnlyOffice edit + view configs for a workspace office file.
         * @description Returns server-signed DocEditor configs (`{server_url, edit, view}`, each
         *     mode an `{config, token}` pair) so the browser can open the file in either
         *     edit or view mode in OnlyOffice without a second round-trip. The OnlyOffice
         *     secret lives only in the backend config and never reaches the browser; each
         *     `token` is an HS256 JWT whose payload is that mode's `config`. `document.url`
         *     and `editorConfig.callbackUrl` point at the backend's internal origin and
         *     embed the caller's JWT as a query `token`; both modes share one freshly
         *     random `document.key` so reopening always re-converts. Shares the workspace
         *     catch-all with `/content`, dispatching on the trailing `/onlyoffice-config`
         *     suffix.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative office file path (catch-all, may include `/`).
                     * @example reports/2026-q2.docx
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed editor config. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnlyOfficeConfigResponse"];
                    };
                };
                /** @description The path resolves to a directory. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description OnlyOffice is not configured (secret empty); editing is disabled. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}/onlyoffice-version-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and sign an OnlyOffice view-only config for a historical version.
         * @description Returns a server-signed view-only DocEditor config
         *     (`{server_url, view:{config, token}}`) so the browser can preview a
         *     specific historical version of a workspace office file in OnlyOffice.
         *     The caller supplies the `versionId` (obtained elsewhere from the
         *     office-vers service); `document.url` points at office-vers for that
         *     version and carries no credential. The OnlyOffice secret lives only in
         *     the backend; `view.token` is an HS256 JWT whose payload is the
         *     `view.config`. Unlike the live-file `/onlyoffice-config` endpoint:
         *     `document.url` targets office-vers (not the backend), `document.key` is
         *     deterministic per `(path, versionId)` (so conversions are cached/shared),
         *     the config is view-only with no `callbackUrl`/`forcesave`, and the local
         *     workspace file is NOT stat-checked (the version's source of truth is
         *     office-vers). Shares the workspace catch-all, dispatching on the
         *     trailing `/onlyoffice-version-config` suffix.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The office-vers (MinIO) version id of the historical version to
                     *     preview. Obtained from the office-vers version-history listing.
                     * @example 7a604dc7-719f-426f-88c4-642313fd2860
                     */
                    versionId: string;
                };
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative office file path (catch-all, may include `/`).
                     * @example reports/2026-q2.docx
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed view-only editor config for the requested version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnlyOfficeVersionConfigResponse"];
                    };
                };
                /** @description The `versionId` query parameter is missing. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description OnlyOffice is not configured (`secret` or `version_service_url` empty). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/onlyoffice-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive an OnlyOffice document-save callback and persist it.
         * @description Endpoint the OnlyOffice DocumentServer POSTs to when a document is saved.
         *     Authenticates via the `token` query parameter (the user JWT embedded in
         *     the signed `callbackUrl`) instead of the Authorization header, since the
         *     callback originates from the DocumentServer container. For save statuses
         *     (2/6) it downloads the edited file from `url` — host-allowlisted to the
         *     configured DocumentServer to mitigate SSRF — and atomically overwrites the
         *     workspace file (capped at the upload size limit). Non-save statuses are
         *     acknowledged without writing. Outcomes use OnlyOffice's `{"error": N}`
         *     convention (0 = ok, non-0 = retry); auth/path errors are normal HTTP 4xx.
         */
        post: {
            parameters: {
                query: {
                    /**
                     * @description Workspace-relative file path to overwrite.
                     * @example reports/2026-q2.docx
                     */
                    path: string;
                    /** @description JWT access token (embedded in the signed callbackUrl). */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnlyOfficeCallbackRequest"];
                };
            };
            responses: {
                /** @description Callback processed; body reports success or a retryable error. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnlyOfficeCallbackResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description OnlyOffice is not configured (secret empty); editing is disabled. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the combined MCP tool catalogue.
         * @description Returns the combined tool catalogue: regular Xizhi registry tools,
         *     tools advertised by configured external MCP servers, and the synthetic
         *     `invoke_chongzhi` / `invoke_liang` agent-invocation tools. Each entry
         *     follows the OpenAI function-tool shape (`type: function`).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tool list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MCPToolsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's skills. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skill list (empty array when none exist). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkillsResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable machine-readable error code.
                 * @example BAD_REQUEST
                 */
                code: string;
                /**
                 * @description Human-readable error description.
                 * @example invalid request body
                 */
                message: string;
            };
        };
        LoginRequest: {
            username: string;
            /** @description User password, verified against the seed-created bcrypt hash. Required only when auth.password_required is true (the default); in passwordless mode the password, if sent, is ignored. */
            password?: string;
        };
        LoginResponse: {
            /**
             * @description The authenticated user's stable id. Used as the `{uuid}` namespace
             *     for the external office-vers versioning service (frontend connects
             *     directly; see add-file-versioning change).
             */
            user_id: string;
            /** @description Signed JWT to send as `Bearer` in subsequent requests. */
            access_token: string;
            /**
             * Format: int64
             * @description Token expiry as a Unix timestamp (seconds).
             */
            expire: number;
            /**
             * @example Bearer
             * @enum {string}
             */
            token_type: "Bearer";
        };
        SessionListEntry: {
            session_id: string;
            title: string;
            /**
             * Format: date-time
             * @description RFC3339 timestamp of the last update.
             */
            update_time: string;
        };
        SessionListResponse: {
            sessions: components["schemas"]["SessionListEntry"][];
        };
        CreateSessionResponse: {
            /**
             * Format: uuid
             * @description Server-generated UUID v7 session identifier.
             * @example 018f9b8a-7c1a-7e6a-8e6a-6c1a7c1a7c1a
             */
            session_id: string;
        };
        Message: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            session_id: string;
            /** Format: date-time */
            msg_time: string;
            /** @enum {string} */
            agent: "user" | "Confucius" | "Chongzhi" | "Liang";
            msg_index: number;
            /** @enum {string} */
            role: "user" | "assistant" | "tool" | "";
            /** @enum {string} */
            event_type: "message" | "token" | "tool_call" | "agent_start" | "agent_end" | "agent_error" | "reasoning";
            content: string;
            /** Format: uuid */
            trace_id: string;
            /** Format: date-time */
            update_time: string;
        };
        SessionMessagesResponse: {
            messages: components["schemas"]["Message"][];
            /** @description Opaque cursor for the next page. Absent on the final page. */
            next_page_token?: string;
        };
        SendMessageRequest: {
            /** @description User message text (must be non-empty). */
            content: string;
        };
        SSEAgentStart: {
            /** @enum {string} */
            type: "agent_start";
            agent: string;
        };
        SSEToken: {
            /** @enum {string} */
            type: "token";
            agent: string;
            /** @description Incremental text token. */
            content: string;
        };
        SSEReasoning: {
            /** @enum {string} */
            type: "reasoning";
            agent: string;
            /** @description Incremental reasoning/thinking token. */
            content: string;
        };
        SSEToolCall: {
            /** @enum {string} */
            type: "tool_call";
            agent: string;
            /** @description Tool name. */
            content: string;
            meta?: {
                args?: {
                    [key: string]: unknown;
                };
            };
        };
        SSEAgentEnd: {
            /** @enum {string} */
            type: "agent_end";
            agent: string;
        };
        SSEAgentError: {
            /** @enum {string} */
            type: "agent_error";
            agent: string;
            /** @description Error message. */
            content: string;
            meta?: {
                error_code?: string;
            };
        };
        SSEDone: {
            /** @enum {string} */
            type: "done";
            meta: {
                usage: {
                    prompt_tokens: number;
                    completion_tokens: number;
                    total_tokens: number;
                };
            };
        };
        FileEntry: {
            name: string;
            /** @enum {string} */
            type: "file" | "dir";
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            update_time: string;
        };
        FileListResponse: {
            files: components["schemas"]["FileEntry"][];
        };
        UploadResponse: {
            /** @description Workspace-relative path of the stored file. */
            path: string;
            /** Format: int64 */
            size: number;
        };
        FileContentResponse: {
            path: string;
            content: string;
            size: number;
        };
        /** @description Body for PUT .../files/{path}/content. */
        WriteContentRequest: {
            /** @description Full text body to write as a whole-file replace (create-or-replace, like xizhi_write_file). */
            content: string;
        };
        /** @description Response for PUT .../files/{path}/content. */
        FileContentWriteResponse: {
            /** @description Workspace-relative path of the written file. */
            path: string;
            /** @description Number of bytes written. */
            size: number;
        };
        UpdateTitleRequest: {
            /** @description New session title (max 20 characters; longer values are truncated). */
            title: string;
        };
        UpdateTitleResponse: {
            session_id: string;
            title: string;
            /** Format: date-time */
            update_time: string;
        };
        RenameRequest: {
            /** @description Workspace-relative destination path. */
            new_path: string;
            /**
             * @description When true and the final destination is an existing file, atomically
             *     replace it. Default false preserves the 409-on-existing-file behavior.
             *     Overwriting an existing directory is rejected with 409 DEST_NOT_EMPTY;
             *     tree merge is not supported.
             * @default false
             */
            overwrite: boolean;
        };
        RenameResponse: {
            old_path: string;
            new_path: string;
        };
        /** @description Body for POST .../files/{path} (strict create of an empty node). */
        CreateNodeRequest: {
            /**
             * @description Leaf kind to create. "file" → empty file (O_CREATE|O_EXCL);
             *     "directory" → empty directory (os.Mkdir). Note this uses "directory",
             *     not the "dir" shorthand used in FileEntry.type.
             * @enum {string}
             */
            type: "file" | "directory";
        };
        /** @description Response for POST .../files/{path}. */
        CreateNodeResponse: {
            /** @description Workspace-relative path of the created node. */
            path: string;
            /** @enum {string} */
            type: "file" | "directory";
        };
        MCPTool: {
            /**
             * @example function
             * @enum {string}
             */
            type: "function";
            name: string;
            description: string;
            /** @description JSON Schema describing the tool's input parameters. */
            parameters: {
                [key: string]: unknown;
            };
        };
        MCPToolsResponse: {
            tools: components["schemas"]["MCPTool"][];
        };
        SkillEntry: {
            /** @description Skill identifier (the subdirectory name containing SKILL.md). */
            name: string;
            /** @description Same as `name`; the skill directory name. */
            filename: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            update_time: string;
        };
        SkillsResponse: {
            skills: components["schemas"]["SkillEntry"][];
        };
        /**
         * @description Server-signed OnlyOffice DocEditor configs for both edit and view modes.
         *     The browser loads api.js from `server_url` and instantiates
         *     `new DocsAPI.DocEditor(id, {...config, token})` for whichever mode it
         *     needs. The OnlyOffice secret never leaves the server — each `token` is
         *     an HS256 JWT whose payload is that mode's `config`, verifiable by the
         *     DocumentServer with the same secret. Because the token signs the whole
         *     config, the frontend cannot switch modes by mutating a config in place;
         *     it must use the pre-signed edit or view token. Both modes share one
         *     freshly random `document.key` (per request).
         */
        OnlyOfficeConfigResponse: {
            /** @description Browser-facing DocumentServer origin (api.js is loaded from here). */
            server_url: string;
            edit: components["schemas"]["OnlyOfficeModeConfig"];
            view: components["schemas"]["OnlyOfficeModeConfig"];
        };
        /**
         * @description Server-signed OnlyOffice DocEditor config for viewing a specific
         *     historical version (view-only). Mirrors one mode of
         *     OnlyOfficeConfigResponse — a single `{config, token}` pair nested under
         *     `view` — so the frontend reuses its existing `view` consumption path. A
         *     historical version is immutable, so only the view mode is returned (no
         *     edit). `document.url` points at the external office-vers service
         *     (`{version_service_url}/documents/{userUUID}/{path}?action=version&versionId=<vid>`)
         *     and carries NO credential (office-vers is unauthenticated by design);
         *     `document.key` is derived deterministically from `(path, versionId)`
         *     (`base32(sha256(path + ":" + versionId))`) so OnlyOffice caches and shares
         *     the conversion across opens/users; the config carries no `callbackUrl`
         *     and no `customization.forcesave` (nothing to save back to an immutable
         *     version).
         */
        OnlyOfficeVersionConfigResponse: {
            /** @description Browser-facing DocumentServer origin (api.js is loaded from here). */
            server_url: string;
            view: components["schemas"]["OnlyOfficeModeConfig"];
        };
        /**
         * @description One signed DocEditor config (edit or view). `config` is the editor
         *     config object; `token` is the HS256 JWT signing exactly that `config`
         *     with the OnlyOffice secret. The edit and view tokens are distinct.
         */
        OnlyOfficeModeConfig: {
            /**
             * @description DocEditor config object. `edit.config` carries `documentType`
             *     (word/cell/slide), `document{fileType, key, title, url,
             *     permissions{edit:true, download:true}}` and `editorConfig{mode:"edit",
             *     callbackUrl, customization{forcesave:true}, user}`. `view.config` is
             *     identical except `document.permissions.edit` is `false` and
             *     `editorConfig{mode:"view", callbackUrl, user}` carries no
             *     `customization.forcesave`. Both share the same `document.key`
             *     (freshly random per request); `document.url` and
             *     `editorConfig.callbackUrl` are rooted at the backend's internal origin
             *     and carry the user JWT as a query `token`.
             */
            config: {
                [key: string]: unknown;
            };
            /** @description HS256 JWT signing this mode's `config` with the OnlyOffice secret; edit and view tokens differ. */
            token: string;
        };
        /**
         * @description OnlyOffice DocumentServer save callback. `status` 2/6 carry the edited
         *     document at `url` and trigger a download + workspace overwrite; other
         *     statuses (1/3/4/7) are acknowledged without writing.
         */
        OnlyOfficeCallbackRequest: {
            /** @description Document state (1=being edited, 2=ready for saving, 3/7=saving error, 4=closed no changes, 6=forcesave). */
            status?: number;
            /** @description Document key the config was signed with. */
            key?: string;
            /** @description URL of the edited document to download (only present on save statuses). */
            url?: string;
        };
        /**
         * @description OnlyOffice callback contract. `error` 0 = success; non-0 makes the
         *     DocumentServer retry. Auth/path errors are reported as normal HTTP 4xx,
         *     not through this body.
         */
        OnlyOfficeCallbackResponse: {
            /** @description 0 on success, non-0 to trigger a DocumentServer retry. */
            error: number;
        };
    };
    responses: {
        /** @description Malformed request body or missing field. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation not permitted (e.g. path outside workspace). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Target resource already exists. */
        AlreadyExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Uploaded file exceeds the size limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
